package com.example.phoenix.context.exception.handler;

public enum ErrorCode {
  API_ERROR_CODE(1000), // == // -------------------------------------------------------
  ALREADY_EXISTS_ERROR_CODE(1100), // ==
  USER_ALREADY_EXISTS(1100),
  BOOK_NOT_FOUND(123),// ==
  ALREADY_EXISTS_SUB_ERROR_CODE(1100), // ==
  USER_PHONE_EXIST(1100), // == // user exist with this number
  ALREADY_PAID_ORDER(1100), // ==
  ALREADY_CANCELED_OR_DELIVERED_ERROR(1100), // ==
  ALREADY_EXIST_PROMO_CODE(1100), // ==
  ALREADY_COURIER_ASSIGNED_CODE(1100), // ==
  ALREADY_USED_PROMO_CODE(1100), // == // -------------------------------------------------------
  ALREADY_ORDER_CLOSED_OR_DELIVERED(
      1100), // -------------------------------------------------------
  NOT_FOUND_ERROR_CODE(1200),
  URL_NOT_FOUND(1201),
  USER_NOT_FOUND(1202),
  STAFF_NOT_FOUND(1202),
  ORDER_NOT_FOUND(1203),
  ORDER_FEEDBACK_NOT_FOUND(1203),
  PRODUCT_NOT_FOUND_IN_BRANCH(1203),
  BRANCH_NOT_FOUND(1204),
  COLLECTOR_NOT_FOUND(1204),
  DRIVER_NOT_FOUND(1205),
  DELIVERY_TARIFF_NOT_FOUND(1206),
  DELIVERY_TARIFF_FOR_CLIENT_NOT_FOUND(1206),
  PRODUCT_NOT_FOUND(1207),
  OTHER_PAYMENT_NOT_FOUND(1208),
  PAYMENT_SETTING_NOT_FOUND(1209),
  NOTIFICATION_SETTINGS_NOT_FOUND(1209),
  PAYME_SUBSCRIBE_SETTING_NOT_FOUND(1209),
  ADDRESS_NOT_FOUND(1209),
  BADGE_NOT_FOUND(1209),
  BANNER_NOT_FOUND(1209),
  BRAND_CATALOG_NOT_FOUND(1209),
  CITY_NOT_FOUND(1209),
  PRODUCT_GROUP_NOT_FOUND(1209),
  OPEN_BRANCHES_NOT_FOUND(1209),
  MERCHANT_NOT_FOUND(1209),
  MERCHANT_CONTACT_NOT_FOUND(1209),
  QR_CODE_NOT_FOUND(1209), // kitchen appga login qilishda ishlatiladi
  USER_REVIEW_NOT_FOUND(1209),
  SMS_CONTENT_NOT_FOUND(1209),
  ADDRESS_TARGET_NOT_FOUND(1209),
  AREA_NOT_FOUND(1209),
  DELIVERY_PRICE_CALCULATE_SETTING_NOT_FOUND(1209),
  FREE_DELIVERY_NOT_FOUND(1209),
  TRANSPORT_NOT_FOUND(1209),
  LOGIST_NOT_FOUND(1209),
  TRANSACTION_NOT_FOUND(1209),
  PROMO_CODE_NOT_FOUND(1209),
  BOT_NOT_FOUND(1209),
  BILLING_TARIFF_NOT_FOUND(1209),
  POSTER_SETTINGS_NOT_FOUND(1209),
  DISCOUNT_NOT_FOUND(1209),
  STOCKTAKING_NOT_FOUND(1209),
  PROVIDER_NOT_FOUND(1209),
  PAYMENT_NOT_FOUND(1209),
  PARTNER_NOT_FOUND(1209),
  ACCOUNT_NOT_FOUND(1209),
  TABLE_NOT_FOUND(1209),
  BTS_CITY_NOT_FOUND(1209),
  HEADER_MISSED(1209),

  DISCOUNT_CANNOT_APPLIED(
      1209), // == // ------------------------------------------------------------
  NULL_POINTER_ERROR_CODE(1300), // ==
  UNEXPECTED_VALUE(1300), // ==
  UNSUPPORTED_OPERATION_ERROR_CODE(1400), // ==
  INVALID_ARGUMENT_ERROR_CODE(1500), // ==
  INVALID_CREDENTIALS_ERROR_CODE(1600), // ==
  INVALID_TOKEN_ERROR_CODE(1700), // ==
  PHONE_BELONGS_TO_YOU(1700), // == // bu telefon raqamni ozgartirganda
  INVALID_DELIVERY_TYPE(1700), // == // agar delivery type yoniq bolmasa yoki Custom bersa
  ORDER_IS_NOT_DELIVERY(1313), // ==
  DELIVERY_IS_NOT_LAMENU(1313), // ==
  OLD_AND_NEW_VALUE_SAME(1313), // ==
  PRODUCT_COUNT_MUST_BE_INTEGER(
      1313), // == // --------------------------------------------------------------
  INVALID_OPERATION_ERROR_CODE(1800), // ==
  PRODUCT_PRICE_LESS_THAN_SETTING(1800), // == // for only delivery order
  PRODUCT_IN_STOP_LIST(1801), // ==
  NOT_SELECTED_ALL_MODIFICATION(1802), // ==
  NOT_SELECTED_MODIFICATION_GROUP(1803), // ==
  INVALID_NUMBER_SELECTED_MODIFICATION_GROUP(
      1804), // == // Invalid number of modifications selected for group %s ,required min %s max %s
  NOT_SELECTED_MODIFICATION(1805), // ==
  INVALID_NUMBER_SELECTED_MODIFICATION(
      1806), // == // Modification %s have been selected more or less
  PROMO_CODE_EXPIRED(1807), // ==
  PROMO_CODE_COUNT_OVER_LIMIT(1807), // ==
  INVALID_ORDER_SUM_FOR_PROMO(1808), // ==
  TOTAL_PRICE_NOT_EQUAL(1808), // ==
  DELIVERY_NOT_AVAILABLE(1808), // ==
  TOTAL_DISCOUNT_NOT_EQUAL(1808), // ==
  PRODUCT_PRICE_NOT_EQUAL(1808), // ==
  PRODUCT_DISCOUNT_NOT_EQUAL(1808), // ==
  CASHBACK_NOT_ENOUGH(1808), // ==
  CANNOT_EDIT_CASHBACK_ORDER(1808), // ==
  PAYMENT_TYPE_NOT_ENABLED(1808), // ==
  REQUIRED_FIELD_MISSED(1888), // ==
  STATUS_NOT_ALLOWED_TO_MANAGE_ORDER(1888), // ==
  NOT_ALLOWED_ALREADY_CREATED_YANDEX_ORDER(1888), // ==
  NOT_ALLOWED_ALREADY_CREATED_MILLENIUM_ORDER(1888), // ==
  NOT_ALLOWED_STATUS(1213), // == // bu statusda buyurtmani ozgartirishga ruxsat yuq
  // -------------------------------------------------------
  // -------------------------------------------------------
  MERCHANT_PAYMENT_NOT_FOUND(1209), // ==
  TICKET_NOT_FOUND(1201), // ==
  TICKET_THEME_NOT_FOUND(1201), // ==
  TEMPLATE_TASK_NOT_FOUND(1201), // ==
  TASK_NOT_FOUND(1201), // ==
  SET_UP_NOT_FOUND(1201), // ==
  LID_NOT_FOUND(1201), // ==
  SMS_SETTING_NOT_FOUND(1201), // ==
  TODO_STATUS_NOT_FOUND(1201), // ==
  LID_STATUS_NOT_FOUND(1201), // ==
  CALL_NOT_FOUND(1201), // ==
  ORDER_UNITS_NOT_FOUND(1201), // ==
  KITCHEN_ORDER_NOT_FOUND(1201), // ==
  NEWS_NOT_FOUND(1201), // ==
  KNOWLEDGE_NOT_FOUND(1201), // ==
  OFFER_NOT_FOUND(1201), // ==
  TODO_NOT_FOUND(1201), // ==
  UNIT_NOT_FOUND(1201), // ==
  ADVERTISEMENT_NOT_FOUND(1201), // ==
  FACTORY_NOT_FOUND(1201), // ==
  UNIT_GROUP_NOT_FOUND(1201), // == // ------------------------------------------------------------
  NOT_ALLOWED_ASSIGN(1213), // == // bu statusda buyurtmani ozgartirishga ruxsat yuq

  SERVICE_TYPE_NOT_DELIVERY(1888), // ==

  DELIVERY_TYPE_NOT_LAMENU(1888), // ==

  DELIVERY_TYPE_NOT_CUSTOM(1888), // ==

  CARD_NOT_VERIFIED(1888), // ==

  NOT_ALLOWED_ASSIGN_ORDER_TO_COURIER(19999), // == // joinOnlyViaOperator ==true

  SESSION_TYPE_NOT_ALLOWED(
      19999), // == // qr code bilan login qilishda ruxsta etilmagan session type

  TOO_MANY_REQUEST(19999), // ==

  CODE_INCORRECT(19999), // ==

  TIME_EXPIRED(19999), // == // --------------------------------------------------------------
  LOCKING_CONFLICT_ERROR_CODE(1900), // ==

  UNAUTHORIZED_ERROR_CODE(2000), // ==

  FORBIDDEN_ERROR_CODE(2100), // ==

  USER_BLOCKED_ERROR_CODE(2200), // ==

  CREATE_FORBIDDEN_ERROR_CODE(2300), // ==

  DELETE_FORBIDDEN_ERROR_CODE(2400), // ==

  LIST_FORBIDDEN_ERROR_CODE(2500), // ==

  RETRIEVE_FORBIDDEN_ERROR_CODE(2600), // ==

  UPDATE_FORBIDDEN_ERROR_CODE(2700), // ==

  JSON_PARSING_ERROR_CODE(2800), // ==

  FILE_DOWNLOAD_ERROR_CODE(2900), // ==

  FILE_REMOVE_ERROR_CODE(3000), // ==

  FILE_UPLOAD_ERROR_CODE(3100), // ==

  TIMEOUT_ERROR_CODE(3200), // ==

  SERVICE_UNAVAILABLE_ERROR_CODE(3300), // ==

  INTERNAL_ERROR_CODE(3400), // ==

  CACHE_IS_NOT_WORKING(3400), // ==

  BAD_REQUEST_CODE(3500), // ==
  YANDEX_ERROR_CODE(3600), // ==
  YANDEX_DISABLE(3600), // ==
  INN_MISSED(3600), // ==
  YANDEX_ORDER_NOT_FOUND(3600), // ==
  MILLINIUM_ERROR_CODE(3600), // ==
  MILLINIUM_ORDER_CANCELED_CODE(3600), // ==
  MILLINIUM_ORDER_NOT_FOUND(3600), // ==
  MILLINIUM_SETTING_NOT_FOUND(3600), // ==

  INVALID_PHONE_NUMBER_CODE(3600), // ==
  INVALID_TYPE(3600), // ==

  PASSWORD_NOT_MATCH_ERROR(3700), // ==
  PAYZE_TRANSACTION_NOT_FOUND(3700), // ==
  NOT_SUPPORT_PAYMENT_TYPE(1234), // ==
  NOT_SUPPORT_DELIVERY_TYPE(1234), // ==
  PAYME_CARD_ERROR(
      3501), // == // An error occurred during registration on Payme. Please make sure the entered

  // information is correct.
  PAYME_CARD_VERIFY_CODE_ERROR(
      3502), // == // An error occurred during registration on Payme. Please make sure the entered
  // information is correct.

  IO_EXCEPTION(3600), // ==
  ALREADY_SEND_NEWS(1234), // ==
  EXPRESS_SETTINGS_NOT_FOUND(3600), // ==
  MODIFIER_NOT_FOUND(1209), // ==
  MODIFICATION_GROUP_NOT_FOUND(1209), // ==
  YANDEX_SETTINGS_NOT_FOUND(3600), // ==
  MERCHANT_SETTINGS_NOT_FOUND(3600), // ==
  ONLINE_PBX_DOMAIN_REQUIRED(1888), // ==
  WRONG_ONLINE_PBX_SETTINGS(1700), // ==
  SERVICE_PRICE_NOT_EQUAL(1808), // ==
  MAX_UPLOAD_SIZE_EXCEEDED(2367), // ==

  // new error code
  ALREADY_BTS_ORDER_EXIST(4161),

  // new errors
  CANNOT_MANAGE_ONLINE_PAYMENTS(1234),
  STORY_INFO_NOT_FOUND(1234),
  STORY_NOT_FOUND(123),
  USER_REGISTERED_AS_STAFF(123),
  INVALID_URL(12); // ==
  public final int value;

  ErrorCode(int value) {
    this.value = value;
  }
}
